### ISSUE TITLE
Lab Re-Order

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/sql-complex-joins-readme#11]
Current order:
- SQL Joins Code Along: https://learn.co/tracks/full-stack-web-development/sql-structured-query-language/table-relations/sql-joins
- SQL Joins Lab: https://learn.co/tracks/full-stack-web-development/sql-structured-query-language/table-relations/sql-crowdfunding-lab
- SQL Complex Joins ReadMe: https://learn.co/tracks/full-stack-web-development/sql-structured-query-language/table-relations/sql-complex-joins

A @reifnotreef pointed out that it might make more sense to do ReadMe - CodeAlong - Lab instead:
- SQL Complex Joins ReadMe: https://learn.co/tracks/full-stack-web-development/sql-structured-query-language/table-relations/sql-complex-joins
- SQL Joins Code Along: https://learn.co/tracks/full-stack-web-development/sql-structured-query-language/table-relations/sql-joins
- SQL Joins Lab: https://learn.co/tracks/full-stack-web-development/sql-structured-query-language/table-relations/sql-crowdfunding-lab

@AnnJohn

**Comment by aturkewi** [comment]
@PeterBell

**Comment by PeterBell** [comment]
That'd be something great for @pletcher and @AnnJohn to confirm/review - thanks for highlighting @aturkewi !

**Comment by pletcher** [comment]
Totally. I'll go ahead and change this.

**Comment by PeterBell** [comment]
Thanks @pletcher !
