### ISSUE TITLE
In examples at bottom, all students' teacher_id is (incorrectly) shown as 1

### ISSUE THREAD

**Issue by miclp** [learn-co-curriculum/sql-complex-joins-readme#13]
Unless I'm not understanding this material fully, it seems that the students named Rob and Sara should have a teacher_id of '2' in the outputs of all the join examples?

Also, the students named Bob and Jessie have their "id" swapped in some of the outputs.  (Bob's id is 3 and Jessie's is 2 in the 'schema' but reported as reversed in some of the outputs.)

**Comment by mendelB** [comment]
Another good call @miclp Thanks!
