### ISSUE TITLE
Full Outer Join results weird

### ISSUE THREAD

**Issue by buckethead1986** [learn-co-curriculum/sql-complex-joins-readme#21]
At the very end of the lesson, in the example of a full outer join, the third row should be Joe, not Steven. Joe's id is 1, not stevens.
id    teacher_name   id      name     teacher_id
---   ------------  ----    ------    -----------
1        Joe         3       Bob          1
1        Joe         1       Dave         1
1        Steven      2       Jessie       1
2        Steven      5       George       2
2        Steven      4       Sara         2
3        Jeff       NULL     NULL        NULL
NULL     NULL        6       Alexis      NULL``

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#23.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @buckethead1986,

Thank you for opening this issue. I just wanted to follow up with you to confirm that this issue has been fixed.

Thank you for your contribution!
