### ISSUE TITLE
Full join table

### ISSUE THREAD

**Issue by popemray00** [learn-co-curriculum/sql-complex-joins-readme#22]
id   teacher_name   id      name     teacher_id
---   ------------  ----    ------    -----------
1        Joe         3       Bob          1
1        Joe         1       Dave         1
1        Steven      2       Jessie       1
2        Steven      5       George       2
2        Steven      4       Sara         2
3        Jeff       NULL     NULL        NULL
NULL     NULL        6       Alexis      NULL
The Full Join table has teacher name steven as an id 1 and id 2 but the id 1 should be joe.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#23.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @popemray00,

Thank you for opening this issue. I just wanted to follow up with you to confirm that this issue has been fixed.

Thank you for your contribution!
