### ISSUE TITLE
I believe the third row, teacher_name should read as Joe.

### ISSUE THREAD

**Issue by hong-werdna** [learn-co-curriculum/sql-complex-joins-readme#25]
id    teacher_name   id      name     teacher_id
---   ------------  ----    ------    -----------
1        Joe         3       Bob          1
1        Joe         1       Dave         1
1        Steven      2       Jessie       1
2        Steven      5       George       2
2        Steven      4       Sara         2
3        Jeff       NULL     NULL        NULL
NULL     NULL        6       Alexis      NULL

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 💙
