### ISSUE TITLE
Incorrect code and output in the "Difference between Inner Join and Outer Join" section

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sql-complex-joins-readme#27]
Hello. In the "Difference between Inner Join and Outer Join" section, the tables are set up like this:
```
TEACHERS TABLE               STUDENTS TABLE
teacher_id                   student_id   |   teacher_id
-----------                  ---------------------------
     1                            1       |     NULL
     2                            2       |     1
     3                            3       |     NULL
```
Then, they show the following code to run (for the Inner Join example):
```
SELECT *
FROM Teachers
INNER JOIN Students
ON Teacher.teacher_id = Student.teacher_id;
```

The lesson then says that the output will be this:
```
teacher_id  |  student_id
--------------------------
 1          |  2
```

I tried this out in the Sandbox and found a few problems. First of all, that SELECT statement will return an error because it is specifying a Teachers, Students, Teacher, and Student table. It should either be:
```
SELECT *
FROM Teacher
INNER JOIN Student
ON Teacher.teacher_id = Student.teacher_id;
```

or

```
SELECT *
FROM Teachers
INNER JOIN Students
ON Teachers.teacher_id = Students.teacher_id;
```

The other problem is that the output is inaccurate. It should also include the teacher_id column from the Students table:
```
teacher_id  |  student_id  |  teacher_id
----------------------------------------
1           |  2           |  1
```

I do not know if the change above needs to be made; my guess is that the teacher_id column from the Students table was not included, in order to avoid confusion over printing the teacher_id twice. However, this is how it would be printed if such code were run.

The issues that I mentioned above are not limited to the Inner Join example; they are also present in the examples for Left Outer Join, Right Outer Join, and Full Outer Join. (I am aware that SQLite3 cannot run Right Outer Join and Full Outer Join; I am assuming that the same issues that I found in the examples for Inner Join and Left Outer Join are also present in the Right and Full Outer Join examples, due to their similar structures.)

Thank you for looking into this!
Sdcrouse

**Comment by Sdcrouse** [comment]
Edit: My apologies for the formatting; some of that text did not copy/paste well from the Learn lesson. I do not know how to fix this. Edit: Fixed!

**Comment by maxwellbenton** [comment]
Hey @Sdcrouse,

Thank you for this feedback. I've fixed the code snippet typos and made them all more consistent. I've also updated the output to reflect the actual result of the join, as you received. This (in my opinion) makes more sense anyway, since we are _joining_ the tables.

Thank you for your contribution!

**Comment by Sdcrouse** [comment]
You're welcome! Thanks for doing that; it makes a lot more sense now, and it better reflects the has-many/belongs-to relationship between teachers and students, too. Also, I finally fixed that Markdown issue I had, just for future reference.
