### ISSUE TITLE
Left outer join first example

### ISSUE THREAD

**Issue by swdecker** [learn-co-curriculum/sql-complex-joins-readme#29]
The first example of left outer join has several typos

SELECT *
FROM Teachers
LEFT OUTER JOIN Students
ON Teachers.teacher_id = Students.teacher_id;

The teachers table only has a column of id, so the command would need to be teachers.id.

also the return should include an id column because thats the column in the teachers table.

**Comment by sgharms** [comment]
Good, eye. Fix coming.
