### ISSUE TITLE
Result Tables in the Example section (Left Outer, Right Outer, Full)

### ISSUE THREAD

**Issue by zachnewburgh** [learn-co-curriculum/sql-complex-joins-readme#8]
teachers.id for teacher_name = "Joe" != students.teacher_id

In plain English: for the teacher named Joe, the right-most column (teacher_id) should reflect Joe's id, which is 2. Instead, it is listed as 1.

**Comment by AnnJohn** [comment]
thanks @zachnewburgh we'll update this very very soon.
